name: flutter_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: 0.13.1
  google_mlkit_text_recognition: 0.15.0
  google_mlkit_document_scanner: 0.4.0
  google_mlkit_object_detection: 0.15.0
  flutter_pdfview: ^1.3.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ml/